# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: ubuntu-latest

steps:
- script: git clone https://${USER}:${PASSWORD}@github.com/capgemini-salvgonz/credentials.git
  displayName: 'Looking for credentials'

- script: |
    ls -l ./credentials/sgn-my-apps.pem
    echo User ${USER}
    echo Password ${PASSWORD}
  displayName: 'Executing remote script'
