# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo 'Clone certificates'
    ssh -i "sgn-my-apps.pem" ec2-user@ec2-3-16-135-225.us-east-2.compute.amazonaws.com
  displayName: 'Run a multi-line script'
