# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: ubuntu-latest

steps:
- script: git clone https://${USER}:${PASSWORD}@github.com/capgemini-salvgonz/credentials.git
  displayName: 'Looking for credentials'

- script:
    ip addr; 
    ls -l ./credentials/2code-keys.pem; 
    mv ./credentials/2code-keys.pem 2code-keys.pem; 
    chmod 400 2code-keys.pem; 
    ssh -o "StrictHostKeyChecking no" -i "2code-keys.pem" ec2-user@ec2-18-144-165-120.us-west-1.compute.amazonaws.com<<EOF
    netstat -tpan 
    bash build.sh $(DB-SECRET)
    EOF;
  displayName: 'Executing remote script'
