# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: ubuntu-latest

steps:
- script: git clone https://${USER}:${PASSWORD}@github.com/capgemini-salvgonz/credentials.git
  displayName: 'Looking for credentials'

- script: |
    ls -l ./credentials/sgn-my-apps.pem
    mv ./credentials/sgn-my-apps.pem sgn-my-apps.pem
    chmod 400 sgn-my-apps.pem
    ssh -o "StrictHostKeyChecking no" -i sgn-my-apps.pem ec2-user@ec2-3-16-135-225.us-east-2.compute.amazonaws.com<<EOF
    echo "Mi password es: " $(PASSWORD)
    bash build.sh
    EOF
  displayName: 'Executing remote script'
